version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/src"
    update_schedule: "live"
    target_branch: "development"
    automerged_updates:
      - match:
          dependency_name: "@types/*"
  - package_manager: "javascript"
    directory: "/src/projects/media/webview"
    update_schedule: "live"
    target_branch: "development"
    automerged_updates:
      - match:
          dependency_name: "@types/*"
